/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonEvent {
        "initialCount": number;
    }
    interface CustomHello {
        "first": string;
        "last": string;
        "middle": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface StatusBadge {
        /**
          * @default false
         */
        "autoRemove": boolean;
        "message": string;
        /**
          * @default false
         */
        "persistent": boolean;
        "status": 'info'|'success'|'warning'|'danger'|'critical'|'secondary';
        "ttl": number | undefined;
    }
    interface TemplateCard {
        /**
          * @default 0
         */
        "accomplishments": number;
        /**
          * @default false
         */
        "addComplementaryActions": boolean;
        "age": number;
        "descriptionText": string;
        "first": string;
        "job": string;
        "last": string;
    }
    interface XIcon {
    }
}
export interface ButtonEventCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLButtonEventElement;
}
declare global {
    interface HTMLButtonEventElementEventMap {
        "countIncreased": number;
    }
    interface HTMLButtonEventElement extends Components.ButtonEvent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLButtonEventElementEventMap>(type: K, listener: (this: HTMLButtonEventElement, ev: ButtonEventCustomEvent<HTMLButtonEventElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLButtonEventElementEventMap>(type: K, listener: (this: HTMLButtonEventElement, ev: ButtonEventCustomEvent<HTMLButtonEventElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLButtonEventElement: {
        prototype: HTMLButtonEventElement;
        new (): HTMLButtonEventElement;
    };
    interface HTMLCustomHelloElement extends Components.CustomHello, HTMLStencilElement {
    }
    var HTMLCustomHelloElement: {
        prototype: HTMLCustomHelloElement;
        new (): HTMLCustomHelloElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLStatusBadgeElement extends Components.StatusBadge, HTMLStencilElement {
    }
    var HTMLStatusBadgeElement: {
        prototype: HTMLStatusBadgeElement;
        new (): HTMLStatusBadgeElement;
    };
    interface HTMLTemplateCardElement extends Components.TemplateCard, HTMLStencilElement {
    }
    var HTMLTemplateCardElement: {
        prototype: HTMLTemplateCardElement;
        new (): HTMLTemplateCardElement;
    };
    interface HTMLXIconElement extends Components.XIcon, HTMLStencilElement {
    }
    var HTMLXIconElement: {
        prototype: HTMLXIconElement;
        new (): HTMLXIconElement;
    };
    interface HTMLElementTagNameMap {
        "button-event": HTMLButtonEventElement;
        "custom-hello": HTMLCustomHelloElement;
        "my-component": HTMLMyComponentElement;
        "status-badge": HTMLStatusBadgeElement;
        "template-card": HTMLTemplateCardElement;
        "x-icon": HTMLXIconElement;
    }
}
declare namespace LocalJSX {
    interface ButtonEvent {
        "initialCount"?: number;
        "onCountIncreased"?: (event: ButtonEventCustomEvent<number>) => void;
    }
    interface CustomHello {
        "first"?: string;
        "last"?: string;
        "middle"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface StatusBadge {
        /**
          * @default false
         */
        "autoRemove"?: boolean;
        "message"?: string;
        /**
          * @default false
         */
        "persistent"?: boolean;
        "status"?: 'info'|'success'|'warning'|'danger'|'critical'|'secondary';
        "ttl"?: number | undefined;
    }
    interface TemplateCard {
        /**
          * @default 0
         */
        "accomplishments"?: number;
        /**
          * @default false
         */
        "addComplementaryActions"?: boolean;
        "age"?: number;
        "descriptionText"?: string;
        "first"?: string;
        "job"?: string;
        "last"?: string;
    }
    interface XIcon {
    }
    interface IntrinsicElements {
        "button-event": ButtonEvent;
        "custom-hello": CustomHello;
        "my-component": MyComponent;
        "status-badge": StatusBadge;
        "template-card": TemplateCard;
        "x-icon": XIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-event": LocalJSX.ButtonEvent & JSXBase.HTMLAttributes<HTMLButtonEventElement>;
            "custom-hello": LocalJSX.CustomHello & JSXBase.HTMLAttributes<HTMLCustomHelloElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "status-badge": LocalJSX.StatusBadge & JSXBase.HTMLAttributes<HTMLStatusBadgeElement>;
            "template-card": LocalJSX.TemplateCard & JSXBase.HTMLAttributes<HTMLTemplateCardElement>;
            "x-icon": LocalJSX.XIcon & JSXBase.HTMLAttributes<HTMLXIconElement>;
        }
    }
}
