/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonEvent {
    }
    interface CustomHello {
        "first": string;
        "last": string;
        "middle": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TemplateCard {
        /**
          * @default 0
         */
        "accomplishments": number;
        "age": number;
        "description": string;
        "first": string;
        "job": string;
        "last": string;
    }
}
declare global {
    interface HTMLButtonEventElement extends Components.ButtonEvent, HTMLStencilElement {
    }
    var HTMLButtonEventElement: {
        prototype: HTMLButtonEventElement;
        new (): HTMLButtonEventElement;
    };
    interface HTMLCustomHelloElement extends Components.CustomHello, HTMLStencilElement {
    }
    var HTMLCustomHelloElement: {
        prototype: HTMLCustomHelloElement;
        new (): HTMLCustomHelloElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTemplateCardElement extends Components.TemplateCard, HTMLStencilElement {
    }
    var HTMLTemplateCardElement: {
        prototype: HTMLTemplateCardElement;
        new (): HTMLTemplateCardElement;
    };
    interface HTMLElementTagNameMap {
        "button-event": HTMLButtonEventElement;
        "custom-hello": HTMLCustomHelloElement;
        "my-component": HTMLMyComponentElement;
        "template-card": HTMLTemplateCardElement;
    }
}
declare namespace LocalJSX {
    interface ButtonEvent {
    }
    interface CustomHello {
        "first"?: string;
        "last"?: string;
        "middle"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TemplateCard {
        /**
          * @default 0
         */
        "accomplishments"?: number;
        "age"?: number;
        "description"?: string;
        "first"?: string;
        "job"?: string;
        "last"?: string;
    }
    interface IntrinsicElements {
        "button-event": ButtonEvent;
        "custom-hello": CustomHello;
        "my-component": MyComponent;
        "template-card": TemplateCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-event": LocalJSX.ButtonEvent & JSXBase.HTMLAttributes<HTMLButtonEventElement>;
            "custom-hello": LocalJSX.CustomHello & JSXBase.HTMLAttributes<HTMLCustomHelloElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "template-card": LocalJSX.TemplateCard & JSXBase.HTMLAttributes<HTMLTemplateCardElement>;
        }
    }
}
